# Generated by Django 5.0.6 on 2024-06-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentdetail',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentDetail_enrollment', to='home.enrollment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.25', '2.25'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_re_grade',
            field=models.CharField(blank=True, choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.25', '2.25'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='midterm_grade',
            field=models.CharField(blank=True, choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.25', '2.25'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20, null=True),
        ),
    ]
