# Generated by Django 4.2.13 on 2024-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_college_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='prospectus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='descriptive_title',
            field=models.CharField(max_length=250),
        ),
    ]
