# Generated by Django 5.0.6 on 2024-05-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_class_schedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_class_schedule', to='home.course'),
            preserve_default=False,
        ),
    ]
