# Generated by Django 5.0.6 on 2024-05-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_class_schedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdetail',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_detail', to='home.student_user'),
            preserve_default=False,
        ),
    ]
