# Generated by Django 4.2.13 on 2024-05-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_prospectus_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_prospectus',
            name='pre_requisit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq1', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='course_prospectus',
            name='pre_requisit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq2', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='course_prospectus',
            name='pre_requisit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq3', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='course_prospectus',
            name='pre_requisit4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq4', to='home.subject'),
        ),
        migrations.AlterField(
            model_name='course_prospectus',
            name='pre_requisit5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq5', to='home.subject'),
        ),
    ]
