# Generated by Django 4.2.13 on 2024-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_course_prospectus_pre_requisit1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_prospectus',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('Summer', 'Summer')], default='1st', max_length=20),
        ),
    ]
