# Generated by Django 5.0.6 on 2024-05-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enrollmentdetail_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentdetail',
            name='scholarship_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollment_detail_scholarship', to='home.scholarship'),
        ),
        migrations.AlterField(
            model_name='enrollmentdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_detail', to='home.student_user'),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_re_grade',
            field=models.CharField(blank=True, choices=[('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='midterm_grade',
            field=models.CharField(blank=True, choices=[('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], max_length=20, null=True),
        ),
    ]
