# Generated by Django 5.0.6 on 2024-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_enrollmentdetail_scholarship_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], default='1st Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentdetail',
            name='student_year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4rth Year', '4th Year')], default='1st Year', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_grade',
            field=models.CharField(choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='final_re_grade',
            field=models.CharField(choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjecttaken',
            name='midterm_grade',
            field=models.CharField(choices=[('not yet graded', 'not yet graded'), ('INC', 'INC'), ('NG', 'NG'), ('in_progress', 'in_progress'), ('5', '5'), ('3', '3'), ('2.75', '2.75'), ('2.5', '2.5'), ('2.23', '2.23'), ('2.0', '2.0'), ('1.75', '1.75'), ('1.5', '1.5'), ('1.25', '1.25'), ('1.0', '1.0')], default='not yet graded', max_length=20),
        ),
    ]
