# Generated by Django 4.2.13 on 2024-05-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
