# Generated by Django 5.0.6 on 2024-05-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_class_schedule_year_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_class_schedule', to='home.faculty_user'),
        ),
    ]
